### ISSUE TITLE
Necessity of full .NET framework

### ISSUE THREAD

**Issue by nholik** [IdentityServer/IdentityServer4.WsFederation#10]
Is it still true that this functionality has to rely on using the 'desktop' .NET framework?  I would like to be able to use this in a .net core linux container.

**Comment by leastprivilege** [comment]
That's still true.

Feel free to port the missing bits to a netstandard library - I would be happy to use that.

**Comment by conterio** [comment]
Any update on anyone porting .net framework stuff to netstandard?

**Comment by leastprivilege** [comment]
I am not aware of that.
