### ISSUE TITLE
Code for Relying Party store using a database

### ISSUE THREAD

**Issue by paramdeepsinghsaini** [IdentityServer/IdentityServer4.WsFederation#11]
Hi,

I am currently using the WSFederation protocol with Identity Server 4. I am using EF migrations for configuration and operational data but I dont want to use AddInMemoryRelyingPartyStore method to add the Relying Parties. Could you add a sample code on how to use the same database (SQl Express) and migrate Relying Party store class and then using DBContext just like we did for configuration data.

Thanks
Paramdeep Singh

**Comment by leastprivilege** [comment]
We don't have a sample. But you can easily do that yourself.

**Comment by paramdeepsinghsaini** [comment]
Hi Dominick,
While creating the migrations for Relying Party class, I created another Entity class which has ClaimMapping of Type List but I do not know how to do it for X509Certificate2. Any ideas?
Thanks
Paramdeep Singh

**Comment by leastprivilege** [comment]
You can serialize the cert to a string - there's a GetBase64 or similar named method on X509Certificate2.
