### ISSUE TITLE
Upgrade to latest IdentityServer4 and aspnetcore version

### ISSUE THREAD

**Issue by Mich-b** [IdentityServer/IdentityServer4.WsFederation#13]
As mentioned [here](https://github.com/IdentityServer/IdentityServer4.WsFederation/pull/12#issuecomment-469658795) , could the aspnetcore version, IdentityServer4 version be upgraded to the respective latest versions?

**Comment by leastprivilege** [comment]
go for it.

**Comment by Mich-b** [comment]
Alexej Kowalew went for it :) => https://github.com/IdentityServer/IdentityServer4.WsFederation/pull/12

Will his pull request be merged in the near future?

**Comment by brockallen** [comment]
The PR is still open, but I'm going to close this issue.
