### ISSUE TITLE
wfresh="0" support and a NuGet package

### ISSUE THREAD

**Issue by RemcoBlok** [IdentityServer/IdentityServer4.WsFederation#15]
Hi,

I am curious what plans there are to have wfresh="0" support added and this repo made available through a NuGet package. This repo is currently not available as a NuGet package where IdentityServer3.WsFederation was made available as a NuGet package. 

I did previously ask in https://github.com/IdentityServer/IdentityServer4.WsFederation/pull/12 if wfresh="0" support could be added and this was added as a task, but that pr is now closed without wfresh="0" support, so I'm not sure if this task is still being tracked. @AlexejKowalew made a fork of the netstandard2.0 branch available as a NuGet package, but now that his PR is merged, I'm not sure what the plans are for that fork and Nuget package. 

I'm also not sure if there are any remaining blocking issues on the netstandard2.0 branch in this repo. I'm happy to host IdentityServer on .NET framework instead of .NET Core, so if the net461 branch is more stable, I'm happy to see wfresh="0" support added to that branch first and made available as NuGet package.

Also happy to help out with adding wfresh="0" support, but not sure which branch or fork to start that will have a NuGet package soonest.

kind regards

Remco

**Comment by leastprivilege** [comment]
There are no plans for a nuget package. It's a sample and I don't have the time to maintain it or add features.

If the code is useful for you, feel free to incorporate it into your code base.

**Comment by scottbrady91** [comment]
We support `wfresh` in the commercial component: https://www.identityserver.com/products/ws-federation

**Comment by 616b2f** [comment]
@RemcoBlok I am working on wsfed support but only for netstandard implementation https://github.com/616b2f/IdentityServer4.WsFederation/pull/1

I appreciate any testing and feedback :)

I also opened issues tab on my fork, so you can open them there directly.
