### ISSUE TITLE
Would using Microsofts WsFederation-Implementation make it less complex?

### ISSUE THREAD

**Issue by Compufreak345** [IdentityServer/IdentityServer4.WsFederation#6]
Hi,

I saw that you added Microsoft.AspNetCore.Authentication.WsFederation to the AspNetCoreWsFederation- project. Would adding this to the IdentityServer4.WsFederation-project make the implementation less complex or is your implementation still the easiest? I tried adding Microsofts WSFederation-middleware to the EF-Quickstart and logically get errors because of the bad subject-claim, probably others will follow. I now need to decide if I should try to get Microsofts WSFederation to work with IdentityServer4 or start from your solution - any hints would be greatly appreciated.

Thanks &  best regards,
Compu

**Comment by leastprivilege** [comment]
Microsoft's WS-Fed handler is the client side. This repo here is the server side.

**Comment by Compufreak345** [comment]
Thanks for the fast response, I mistook this repository to be a client-example. Do you know of any examples for the WSFederation client-side? I didn't find any at the [Quickstarts](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts).

**Comment by leastprivilege** [comment]
There's a client sample here..

**Comment by Compufreak345** [comment]
Sorry for bothering you again, but did you miss to put a link at your last response?
